The db_type field must take a second 'connection' argument, even though unused, otherwise one gets an 'unexpected keyword argument connection' TypeError